#Requires -Version 7.0
<#
.SYNOPSIS
    Reproducible vendoring of the portable runtime for autodeploy-desktop.

.DESCRIPTION
    Downloads and extracts:
      1. PowerShell 7.4.x portable (win-x64 ZIP from GitHub Releases) → pwsh/
      2. A minimal, relocatable MSYS2 subtree → runtime/
         containing: xorriso.exe, rsync.exe, bash.exe, msys-2.0.dll
         and ALL transitive DLL dependencies (computed via ntldd or ldd).
      3. runtime/etc/fstab mapping Windows drives to /mnt/<drive> (WSL convention).

    The script is idempotent: it skips downloads when the target directory already
    contains the expected binaries with a matching version marker.

    DEPENDENCY CLOSURE APPROACH (plan §3b)
    ----------------------------------------
    We drive a local MSYS2 installation to install xorriso + rsync, then use ntldd
    (or MSYS2's ldd) to compute the full DLL dependency closure, and copy only those
    files into runtime/.  This produces a self-contained, relocatable subtree that
    runs on a clean Windows machine with no MSYS2 installation required.

    REQUIREMENTS (developer machine only — not shipped):
      - MSYS2 installed at $env:MSYS2_ROOT (default: C:\msys64)
      - OR: set $env:MSYS2_ROOT to a custom path
      - Internet access (to download pwsh zip + pacman packages)
      - Run as the account that owns MSYS2 (pacman writes to MSYS2's own dirs)

    OUTPUT (gitignored, regenerated by this script):
      pwsh/          ← PowerShell 7.4.x portable
      runtime/       ← MSYS2 minimal relocatable subtree

.NOTES
    Pin management: bump $PWSH_VERSION to upgrade PowerShell.
    The MSYS2 packages are fetched at the latest version available from the
    pacman mirror at run time; pin by downloading a specific .pkg.tar.zst from
    the MSYS2 package archive if reproducibility of the MSYS2 packages matters.
#>

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# ── Pinned versions ──────────────────────────────────────────────────────────
# PowerShell 7.4.10 — win-x64 official release.
# To upgrade: change $PWSH_VERSION and update $PWSH_SHA256 from the release page:
#   https://github.com/PowerShell/PowerShell/releases/tag/v7.4.10
$PWSH_VERSION = '7.4.10'
$PWSH_SHA256  = 'E91EB7F4AF5B16D1027DC0FCF3DBEF7E34CF47F1AC25B5D8B99DBE55C27E7CEF'

$PWSH_URL = "https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/PowerShell-${PWSH_VERSION}-win-x64.zip"

# ── Paths ─────────────────────────────────────────────────────────────────────
$RepoRoot   = $PSScriptRoot | Split-Path -Parent
$PwshDir    = Join-Path $RepoRoot 'pwsh'
$RuntimeDir = Join-Path $RepoRoot 'runtime'
$TempDir    = Join-Path ([System.IO.Path]::GetTempPath()) "autodeploy-fetch-$$"

# MSYS2 installation root (developer machine only — never shipped).
# Override by setting $env:MSYS2_ROOT before calling this script.
$Msys2Root  = if ($env:MSYS2_ROOT) { $env:MSYS2_ROOT } else { 'C:\msys64' }
$Msys2Bash  = Join-Path $Msys2Root 'usr\bin\bash.exe'
$Msys2Pacman = Join-Path $Msys2Root 'usr\bin\pacman.exe'

# ── Helpers ──────────────────────────────────────────────────────────────────
function Write-Step([string]$Msg) {
    Write-Host "  --> $Msg" -ForegroundColor Cyan
}

function Write-Done([string]$Msg) {
    Write-Host "  [OK] $Msg" -ForegroundColor Green
}

function Verify-SHA256([string]$File, [string]$Expected) {
    Write-Step "Verifying SHA-256 of $(Split-Path $File -Leaf) ..."
    $actual = (Get-FileHash -Algorithm SHA256 -LiteralPath $File).Hash
    if ($actual -ne $Expected.ToUpperInvariant()) {
        throw "SHA-256 mismatch for $File`n  expected: $($Expected.ToUpperInvariant())`n  actual:   $actual"
    }
    Write-Done "Hash OK"
}

function Invoke-Download([string]$Url, [string]$Dest) {
    Write-Step "Downloading $(Split-Path $Dest -Leaf) ..."
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri $Url -OutFile $Dest -UseBasicParsing
    Write-Done "Downloaded $(Split-Path $Dest -Leaf)"
}

# Runs a command inside MSYS2 bash (MSYS shell, not MINGW).
function Invoke-Msys2([string[]]$Args, [string]$Description = '') {
    if (-not (Test-Path $Msys2Bash)) {
        throw "MSYS2 bash not found at '$Msys2Bash'. Set `$env:MSYS2_ROOT or install MSYS2."
    }
    $joined = $Args -join ' '
    Write-Step "MSYS2: $Description"
    & $Msys2Bash --login -c $joined
    if ($LASTEXITCODE -ne 0) {
        throw "MSYS2 command failed (exit $LASTEXITCODE): $joined"
    }
}

# ── Step 1 : PowerShell 7 portable ───────────────────────────────────────────
Write-Host "`nStep 1/3 — PowerShell $PWSH_VERSION portable" -ForegroundColor Yellow

$pwshMarker = Join-Path $PwshDir '.version'
if ((Test-Path $pwshMarker) -and ((Get-Content $pwshMarker -Raw).Trim() -eq $PWSH_VERSION)) {
    Write-Done "pwsh/ already at version $PWSH_VERSION — skipping download."
}
else {
    New-Item -ItemType Directory -Force -Path $TempDir | Out-Null
    $zipPath = Join-Path $TempDir "PowerShell-${PWSH_VERSION}-win-x64.zip"

    Invoke-Download $PWSH_URL $zipPath
    Verify-SHA256   $zipPath $PWSH_SHA256

    Write-Step "Extracting to pwsh/ ..."
    # Wipe existing dir to avoid stale files from an older version.
    if (Test-Path $PwshDir) { Remove-Item -Recurse -Force $PwshDir }
    New-Item -ItemType Directory -Force -Path $PwshDir | Out-Null

    Expand-Archive -LiteralPath $zipPath -DestinationPath $PwshDir -Force
    Set-Content -Path $pwshMarker -Value $PWSH_VERSION -Encoding UTF8
    Write-Done "pwsh/ populated (PowerShell $PWSH_VERSION)"
}

$pwshExe = Join-Path $PwshDir 'pwsh.exe'
if (-not (Test-Path $pwshExe)) {
    throw "Expected $pwshExe not found after extraction — check the zip structure."
}

# ── Step 2 : MSYS2 minimal runtime ───────────────────────────────────────────
Write-Host "`nStep 2/3 — MSYS2 portable runtime (xorriso + rsync + bash + DLLs)" -ForegroundColor Yellow

$runtimeMarker = Join-Path $RuntimeDir '.version'
# We use a simple string "msys2-<pacman-db-epoch>" as the marker. For full
# reproducibility, pin specific package versions from the MSYS2 package archive.
$runtimeMarkerExpected = 'msys2-xorriso-rsync'

if ((Test-Path $runtimeMarker) -and ((Get-Content $runtimeMarker -Raw).Trim() -eq $runtimeMarkerExpected)) {
    Write-Done "runtime/ already populated — skipping MSYS2 install step."
}
else {
    if (-not (Test-Path $Msys2Root)) {
        throw @"
MSYS2 not found at '$Msys2Root'.
To build the runtime you need MSYS2 installed (https://www.msys2.org/).
Set `$env:MSYS2_ROOT if you installed it elsewhere.
The runtime/ directory is gitignored and must be rebuilt per the plan §3b.
"@
    }

    # Ensure pacman is up to date and packages are installed.
    Write-Step "Updating pacman db (keyring + core) ..."
    & $Msys2Bash --login -c 'pacman -Syu --noconfirm --noprogressbar 2>&1 | tail -5'
    # Second pass needed after keyring update.
    & $Msys2Bash --login -c 'pacman -Su  --noconfirm --noprogressbar 2>&1 | tail -5'

    Write-Step "Installing xorriso and rsync via pacman ..."
    Invoke-Msys2 @('pacman -S --noconfirm --needed xorriso rsync') `
                 -Description 'pacman -S xorriso rsync'

    # ── DLL dependency closure ─────────────────────────────────────────────
    # We use ntldd (Windows-aware ldd) from the MSYS2 package ntldd-git, or fall
    # back to ldd (MSYS2 ldd only shows MSYS DLLs).  The closure script below:
    #   1. Runs ldd on each target binary.
    #   2. Recursively resolves each found DLL.
    #   3. Copies every file under MSYS2_ROOT/usr/bin into the staging area.
    #
    # Note: ntldd shows system DLLs (kernel32, ucrtbase, etc.) which we EXCLUDE
    # because they are always present on Windows. We only bundle MSYS-specific DLLs
    # (files that live under $MSYS2_ROOT).
    Write-Step "Installing ntldd for dependency closure ..."
    & $Msys2Bash --login -c 'pacman -S --noconfirm --needed mingw-w64-x86_64-ntldd-git 2>/dev/null || pacman -S --noconfirm --needed ntldd 2>/dev/null || true'

    Write-Step "Computing DLL dependency closure ..."
    # Shell script executed inside MSYS2 to build the file list.
    $closureScript = @'
#!/bin/bash
set -euo pipefail

MSYS2_USR_BIN="/usr/bin"
STAGE="/tmp/runtime-stage"
rm -rf "$STAGE"
mkdir -p "$STAGE/usr/bin"

# Target executables we must ship.
TARGETS=("xorriso" "rsync" "bash")

# Compute closure: for each binary, collect all MSYS-resident DLL deps.
declare -A seen
collect_deps() {
    local bin="$1"
    local full
    if [[ "$bin" == *.exe ]]; then
        full="$bin"
    else
        full="${MSYS2_USR_BIN}/${bin}.exe"
        [[ -f "$full" ]] || full="${MSYS2_USR_BIN}/${bin}"
    fi
    [[ -f "$full" ]] || { echo "WARNING: $full not found, skipping" >&2; return; }

    # Use ldd (built-in MSYS2) to list deps.  ntldd gives more complete results.
    local deps
    if command -v ntldd &>/dev/null; then
        # ntldd outputs "  NAME => PATH (0xADDR)"
        deps=$(ntldd -R "$full" 2>/dev/null | awk '{print $3}' | grep -i 'msys64\|msys2' | tr '\\' '/' | sed 's|.*bin/||' || true)
    else
        deps=$(ldd "$full" 2>/dev/null | awk '{print $1}' | grep -v '^/' | tr '\\' '/' | sed 's|.*/||' || true)
    fi

    for dep in $deps; do
        dep_name=$(basename "$dep")
        [[ "${seen[$dep_name]+_}" ]] && continue
        seen[$dep_name]=1
        local dep_path="${MSYS2_USR_BIN}/${dep_name}"
        if [[ -f "$dep_path" ]]; then
            cp "$dep_path" "$STAGE/usr/bin/"
            collect_deps "$dep_path"
        fi
    done
}

# Copy the primary binaries first.
for t in "${TARGETS[@]}"; do
    src="${MSYS2_USR_BIN}/${t}.exe"
    [[ -f "$src" ]] || src="${MSYS2_USR_BIN}/${t}"
    if [[ -f "$src" ]]; then
        cp "$src" "$STAGE/usr/bin/"
        seen["$(basename $src)"]=1
        collect_deps "$src"
    else
        echo "ERROR: target binary not found: $t" >&2
        exit 1
    fi
done

# Always include msys-2.0.dll (the MSYS POSIX emulation layer) — required by all.
MSY="msys-2.0.dll"
if [[ -f "${MSYS2_USR_BIN}/${MSY}" ]]; then
    cp "${MSYS2_USR_BIN}/${MSY}" "$STAGE/usr/bin/"
fi

# Summary
echo "--- DLL closure ---"
ls "$STAGE/usr/bin/" | sort
echo "--- end closure ($(ls $STAGE/usr/bin/ | wc -l) files) ---"
echo "$STAGE"
'@

    $closureScriptPath = Join-Path $TempDir 'build-closure.sh'
    # Write with LF line endings (MSYS2 bash requires Unix line endings)
    [System.IO.File]::WriteAllText($closureScriptPath, $closureScript, [System.Text.Encoding]::UTF8)

    # Convert path to MSYS2 POSIX form.
    $msysScriptPath = $closureScriptPath -replace '^([A-Z]):\\', '/mnt/$1/' -replace '\\', '/'
    $msysScriptPath = $msysScriptPath -replace '/mnt/([A-Z])/', { '/mnt/' + $_.Value[5].ToString().ToLower() + '/' }

    # Simpler approach: pass the Windows path and let bash handle it.
    $winTempDir = $TempDir
    $msysTemp   = '/' + ($winTempDir -replace '^([A-Za-z]):\\', { $_.Value[0].ToString().ToLower() + '/' }) -replace '\\', '/'

    & $Msys2Bash --login -c "bash '$msysTemp/build-closure.sh' 2>&1"
    if ($LASTEXITCODE -ne 0) {
        throw "Dependency closure script failed."
    }

    # Copy staged files from MSYS2 /tmp/runtime-stage into our runtime/.
    $msys2TmpStage = Join-Path $Msys2Root 'tmp\runtime-stage'
    if (-not (Test-Path $msys2TmpStage)) {
        throw "Expected staging directory not found: $msys2TmpStage"
    }

    Write-Step "Copying DLL closure into runtime/ ..."
    if (Test-Path $RuntimeDir) { Remove-Item -Recurse -Force $RuntimeDir }
    New-Item -ItemType Directory -Force -Path (Join-Path $RuntimeDir 'usr\bin') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $RuntimeDir 'etc') | Out-Null

    $stageBin = Join-Path $msys2TmpStage 'usr\bin'
    if (Test-Path $stageBin) {
        Copy-Item -Path "$stageBin\*" -Destination (Join-Path $RuntimeDir 'usr\bin') -Recurse -Force
    } else {
        throw "Stage bin dir not found: $stageBin"
    }

    Set-Content -Path $runtimeMarker -Value $runtimeMarkerExpected -Encoding UTF8
    Write-Done "runtime/ populated"

    # Validate that key binaries are present.
    foreach ($bin in @('xorriso.exe', 'rsync.exe', 'bash.exe', 'msys-2.0.dll')) {
        $p = Join-Path $RuntimeDir "usr\bin\$bin"
        if (-not (Test-Path $p)) {
            Write-Warning "Expected binary missing: $p — check the closure script output above."
        }
    }
}

# ── Step 3 : runtime/etc/fstab ───────────────────────────────────────────────
Write-Host "`nStep 3/3 — Writing runtime/etc/fstab" -ForegroundColor Yellow

$etcDir   = Join-Path $RuntimeDir 'etc'
$fstabPath = Join-Path $etcDir 'fstab'

New-Item -ItemType Directory -Force -Path $etcDir | Out-Null

# MSYS2 fstab syntax: <Windows-path>  <mount-point>  <type>  <options>  <dump>  <pass>
#
# CRITICAL (plan risk #1): autodeploy.ps1 calls `wsl xorriso` and likely
# constructs paths like /mnt/c/Users/… mirroring the WSL convention.
# MSYS2 normally mounts C: at /c — this fstab remaps it to /mnt/c so that
# the same path strings work in both WSL and MSYS2 contexts.
#
# We pre-populate the common drive letters; MSYS2 itself will NOT auto-mount
# drives that are not listed here, so the list is exhaustive for A-Z.
# Add or remove entries if you only need specific drives.
$fstabContent = @'
# autodeploy-desktop — MSYS2 portable fstab
# Mount Windows drives at /mnt/<drive> to mirror the WSL path convention.
# autodeploy.ps1 uses wsl-style paths (/mnt/c/...) — this file ensures
# MSYS2 resolves them identically to WSL.
#
# Format: <windows-path>  <mount-point>  <type>  <options>  <dump>  <pass>

none  /  cygdrive  binary,posix=0,noacl,user  0  0

C:/   /mnt/c  ntfs  binary,posix=0,noacl,user  0  0
D:/   /mnt/d  ntfs  binary,posix=0,noacl,user  0  0
E:/   /mnt/e  ntfs  binary,posix=0,noacl,user  0  0
F:/   /mnt/f  ntfs  binary,posix=0,noacl,user  0  0
G:/   /mnt/g  ntfs  binary,posix=0,noacl,user  0  0
H:/   /mnt/h  ntfs  binary,posix=0,noacl,user  0  0
I:/   /mnt/i  ntfs  binary,posix=0,noacl,user  0  0
J:/   /mnt/j  ntfs  binary,posix=0,noacl,user  0  0
K:/   /mnt/k  ntfs  binary,posix=0,noacl,user  0  0
L:/   /mnt/l  ntfs  binary,posix=0,noacl,user  0  0
M:/   /mnt/m  ntfs  binary,posix=0,noacl,user  0  0
N:/   /mnt/n  ntfs  binary,posix=0,noacl,user  0  0
O:/   /mnt/o  ntfs  binary,posix=0,noacl,user  0  0
P:/   /mnt/p  ntfs  binary,posix=0,noacl,user  0  0
Q:/   /mnt/q  ntfs  binary,posix=0,noacl,user  0  0
R:/   /mnt/r  ntfs  binary,posix=0,noacl,user  0  0
S:/   /mnt/s  ntfs  binary,posix=0,noacl,user  0  0
T:/   /mnt/t  ntfs  binary,posix=0,noacl,user  0  0
U:/   /mnt/u  ntfs  binary,posix=0,noacl,user  0  0
V:/   /mnt/v  ntfs  binary,posix=0,noacl,user  0  0
W:/   /mnt/w  ntfs  binary,posix=0,noacl,user  0  0
X:/   /mnt/x  ntfs  binary,posix=0,noacl,user  0  0
Y:/   /mnt/y  ntfs  binary,posix=0,noacl,user  0  0
Z:/   /mnt/z  ntfs  binary,posix=0,noacl,user  0  0
'@

# Write with LF line endings (MSYS2 expects Unix line endings in fstab).
$fstabBytes = [System.Text.Encoding]::UTF8.GetBytes($fstabContent)
[System.IO.File]::WriteAllBytes($fstabPath, $fstabBytes)
Write-Done "runtime/etc/fstab written"

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Host "`n=== fetch-runtime complete ===" -ForegroundColor Green
Write-Host "  pwsh/          PowerShell $PWSH_VERSION ($(Split-Path $PwshDir -Leaf))"
if (Test-Path (Join-Path $RuntimeDir 'usr\bin\xorriso.exe')) {
    $runtimeFiles = (Get-ChildItem -Path (Join-Path $RuntimeDir 'usr\bin') -File).Count
    Write-Host "  runtime/       MSYS2 portable ($runtimeFiles files in usr/bin)"
} else {
    Write-Host "  runtime/       MSYS2 subtree (run on a machine with MSYS2 to populate)"
}
Write-Host "  runtime/etc/fstab  drives A-Z mounted at /mnt/<drive>"
Write-Host ""
Write-Host "To verify the dependency closure on a clean VM (plan §10, P3):" -ForegroundColor DarkCyan
Write-Host "  .\bin\wsl.exe xorriso --version" -ForegroundColor DarkCyan
Write-Host "  .\bin\wsl.exe rsync --version" -ForegroundColor DarkCyan
